"""
Risk Agent - Base class for risk management agents.
"""

import asyncio
import logging
from abc import abstractmethod
from dataclasses import dataclass
from datetime import datetime
from typing import Any, Optional

from ...orchestrator.agent_manager import AgentConfig
from ...orchestrator.communicator import Communicator, Message, MessagePriority
from ...orchestrator.risk_enforcer import RiskEnforcer, RiskMetrics
from .base_agent import AgentMetrics, BaseAgent

logger = logging.getLogger(__name__)


@dataclass
class RiskAlert:
    """Risk alert generated by risk monitoring."""
    alert_type: str  # "warning", "critical", "breach"
    message: str
    metric: str
    current_value: float
    threshold: float
    agent_id: Optional[str] = None
    action_taken: Optional[str] = None


class RiskAgent(BaseAgent):
    """
    Base class for risk management agents.
    
    Risk agents are responsible for:
    - Monitoring risk metrics
    - Generating risk alerts
    - Taking protective actions
    - Enforcing compliance
    
    Inherited by:
    - RiskManager
    - PortfolioRebalancer
    - PnLTracker
    - ComplianceMonitor
    """
    
    def __init__(
        self,
        config: AgentConfig,
        communicator: Communicator,
        risk_enforcer: RiskEnforcer,
    ) -> None:
        """
        Initialize the RiskAgent.
        
        Args:
            config: Agent configuration.
            communicator: Communicator for messaging.
            risk_enforcer: RiskEnforcer instance to monitor.
        """
        super().__init__(config, communicator)
        self._risk_enforcer = risk_enforcer
        self._monitoring_task: Optional[asyncio.Task] = None
        self._monitoring_interval: float = 10.0
        self._alerts: list[RiskAlert] = []
        self._breach_actions_enabled: bool = True
    
    @abstractmethod
    async def check_risk_metrics(self, metrics: RiskMetrics) -> list[RiskAlert]:
        """
        Check risk metrics and generate alerts.
        
        Args:
            metrics: Current risk metrics.
            
        Returns:
            List of risk alerts.
        """
        pass
    
    @abstractmethod
    async def take_protective_action(
        self,
        alert: RiskAlert,
    ) -> Optional[str]:
        """
        Take protective action based on alert.
        
        Args:
            alert: The risk alert.
            
        Returns:
            Description of action taken, or None.
        """
        pass
    
    async def on_start(self) -> None:
        """Start risk monitoring."""
        await self.subscribe("risk")
        await self.subscribe("trades")
        await self.subscribe("system")
        
        # Start monitoring task
        self._monitoring_task = asyncio.create_task(self._monitoring_loop())
        
        self.log_info(f"RiskAgent {self._config.name} started")
    
    async def on_stop(self) -> None:
        """Stop risk monitoring."""
        if self._monitoring_task:
            self._monitoring_task.cancel()
            try:
                await self._monitoring_task
            except asyncio.CancelledError:
                pass
        
        self.log_info(f"RiskAgent {self._config.name} stopped")
    
    async def on_message(self, message: Message) -> None:
        """Handle incoming messages."""
        if message.message_type == "risk_update":
            # Process risk update
            await self._process_risk_update(message.payload)
        
        elif message.message_type == "trade_approved":
            # Log approved trade
            trade = message.payload.get("trade", {})
            self.log_info(
                f"Trade approved: {trade.get('agent_id')} {trade.get('side')} "
                f"{trade.get('symbol')} @ {trade.get('price')}"
            )
        
        elif message.message_type == "breach_alert":
            # Handle breach alert from another risk agent
            alert_data = message.payload.get("alert", {})
            self.log_warning(f"Breach alert received: {alert_data.get('message')}")
    
    async def _process_risk_update(self, payload: dict[str, Any]) -> None:
        """Process risk update data."""
        try:
            metrics_data = payload.get("metrics", {})
            metrics = RiskMetrics(
                total_exposure=metrics_data.get("total_exposure", 0),
                daily_pnl=metrics_data.get("daily_pnl", 0),
                daily_loss=metrics_data.get("daily_loss", 0),
                max_drawdown=metrics_data.get("max_drawdown", 0),
                current_drawdown=metrics_data.get("current_drawdown", 0),
                portfolio_value=metrics_data.get("portfolio_value", 0),
                open_positions=metrics_data.get("open_positions", 0),
                largest_position=metrics_data.get("largest_position", 0),
            )
            
            # Check metrics
            alerts = await self.check_risk_metrics(metrics)
            
            for alert in alerts:
                self._alerts.append(alert)
                
                # Broadcast alert
                await self._broadcast_alert(alert)
                
                # Take protective action if enabled
                if self._breach_actions_enabled and alert.alert_type in ("critical", "breach"):
                    action = await self.take_protective_action(alert)
                    if action:
                        alert.action_taken = action
                        self.log_warning(f"Protective action taken: {action}")
                
        except Exception as e:
            self.log_error(f"Error processing risk update: {e}")
            self.increment_errors()
    
    async def _broadcast_alert(self, alert: RiskAlert) -> None:
        """Broadcast a risk alert."""
        priority = (
            MessagePriority.CRITICAL
            if alert.alert_type == "breach"
            else MessagePriority.HIGH
        )
        
        await self.broadcast(
            channel="alerts",
            message_type="risk_alert",
            payload={
                "alert": {
                    "type": alert.alert_type,
                    "message": alert.message,
                    "metric": alert.metric,
                    "current_value": alert.current_value,
                    "threshold": alert.threshold,
                    "agent_id": alert.agent_id,
                    "action_taken": alert.action_taken,
                    "timestamp": datetime.utcnow().timestamp(),
                },
                "source_agent": self.agent_id,
            },
            priority=priority,
        )
    
    async def _monitoring_loop(self) -> None:
        """Main risk monitoring loop."""
        while self._state.value != "stopped":
            try:
                # Get current metrics
                metrics = self._risk_enforcer.get_metrics()
                
                # Check metrics
                alerts = await self.check_risk_metrics(metrics)
                
                for alert in alerts:
                    self._alerts.append(alert)
                    await self._broadcast_alert(alert)
                    
                    if self._breach_actions_enabled and alert.alert_type in ("critical", "breach"):
                        action = await self.take_protective_action(alert)
                        if action:
                            alert.action_taken = action
                            self.log_warning(f"Protective action taken: {action}")
                
                await asyncio.sleep(self._monitoring_interval)
                
            except asyncio.CancelledError:
                break
            except Exception as e:
                self.log_error(f"Monitoring loop error: {e}")
                self.increment_errors()
                await asyncio.sleep(self._monitoring_interval)
    
    def get_recent_alerts(self, limit: int = 10) -> list[RiskAlert]:
        """Get recent risk alerts."""
        return self._alerts[-limit:]
    
    def get_alerts_by_type(self, alert_type: str) -> list[RiskAlert]:
        """Get alerts by type."""
        return [a for a in self._alerts if a.alert_type == alert_type]
    
    async def emergency_stop(self, reason: str) -> None:
        """
        Trigger emergency stop of all trading.
        
        Args:
            reason: Reason for emergency stop.
        """
        self.log_warning(f"EMERGENCY STOP triggered: {reason}")
        
        # Broadcast emergency stop
        await self.broadcast(
            channel="system",
            message_type="emergency_stop",
            payload={
                "reason": reason,
                "agent_id": self.agent_id,
                "timestamp": datetime.utcnow().timestamp(),
            },
            priority=MessagePriority.CRITICAL,
        )
