"""
Strategy Agent - Base class for trading strategy agents.
"""

import asyncio
import logging
from abc import abstractmethod
from dataclasses import dataclass
from datetime import datetime
from typing import Any, Optional

from ...orchestrator.agent_manager import AgentConfig
from ...orchestrator.communicator import Communicator, Message, MessagePriority
from ...orchestrator.risk_enforcer import RiskDecision, RiskEnforcer, TradeRequest
from .base_agent import AgentMetrics, BaseAgent

logger = logging.getLogger(__name__)


@dataclass
class Signal:
    """Trading signal generated by a strategy."""
    symbol: str
    side: str  # "buy" or "sell"
    strength: float  # 0.0 to 1.0
    entry_price: float
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    size: float = 0.0
    metadata: dict[str, Any] = None
    
    def __post_init__(self) -> None:
        if self.metadata is None:
            self.metadata = {}


class StrategyAgent(BaseAgent):
    """
    Base class for trading strategy agents.
    
    Strategy agents are responsible for:
    - Analyzing market data
    - Generating trading signals
    - Managing positions
    - Coordinating with execution agents
    
    Inherited by:
    - Arbitrage
    - Scalping
    - Grid
    - Momentum
    """
    
    def __init__(
        self,
        config: AgentConfig,
        communicator: Communicator,
        risk_enforcer: RiskEnforcer,
    ) -> None:
        """
        Initialize the StrategyAgent.
        
        Args:
            config: Agent configuration.
            communicator: Communicator for messaging.
            risk_enforcer: RiskEnforcer for trade validation.
        """
        super().__init__(config, communicator)
        self._risk_enforcer = risk_enforcer
        self._active_signals: dict[str, Signal] = {}
        self._positions: dict[str, dict[str, Any]] = {}
        self._symbols: list[str] = []
        self._analysis_task: Optional[asyncio.Task] = None
    
    @abstractmethod
    async def analyze(self, market_data: dict[str, Any]) -> list[Signal]:
        """
        Analyze market data and generate trading signals.
        
        Args:
            market_data: Market data to analyze.
            
        Returns:
            List of generated trading signals.
        """
        pass
    
    async def on_start(self) -> None:
        """Start strategy processing."""
        # Subscribe to data channels
        await self.subscribe("data")
        await self.subscribe("trades")
        await self.subscribe("strategy")
        
        # Start analysis task
        self._analysis_task = asyncio.create_task(self._analysis_loop())
        
        self.log_info(f"StrategyAgent {self._config.name} started")
    
    async def on_stop(self) -> None:
        """Stop strategy processing."""
        if self._analysis_task:
            self._analysis_task.cancel()
            try:
                await self._analysis_task
            except asyncio.CancelledError:
                pass
        
        self.log_info(f"StrategyAgent {self._config.name} stopped")
    
    async def on_message(self, message: Message) -> None:
        """Handle incoming messages."""
        if message.message_type == "data_update":
            # Process market data
            data = message.payload.get("data", {})
            await self._process_market_data(data)
        
        elif message.message_type == "subscribe":
            symbols = message.payload.get("symbols", [])
            self._symbols = symbols
            self.log_info(f"Subscribed to symbols: {symbols}")
        
        elif message.message_type == "position_update":
            # Update position tracking
            symbol = message.payload.get("symbol")
            position = message.payload.get("position", {})
            if symbol:
                self._positions[symbol] = position
    
    async def _process_market_data(self, data: dict[str, Any]) -> None:
        """Process market data and generate signals."""
        try:
            signals = await self.analyze(data)
            
            for signal in signals:
                # Store signal
                self._active_signals[signal.symbol] = signal
                
                # Validate signal through risk enforcer
                validation = await self._validate_signal(signal)
                
                if validation.decision in (
                    RiskDecision.APPROVED,
                    RiskDecision.APPROVED_WITH_CONDITIONS,
                ):
                    # Send to execution agent
                    await self._send_for_execution(signal, validation)
                else:
                    self.log_warning(
                        f"Signal rejected for {signal.symbol}: {validation.reason}"
                    )
                    
        except Exception as e:
            self.log_error(f"Error processing market data: {e}")
            self.increment_errors()
    
    async def _validate_signal(self, signal: Signal) -> Any:
        """Validate a trading signal against risk limits."""
        trade_request = TradeRequest(
            agent_id=self.agent_id,
            symbol=signal.symbol,
            side=signal.side,
            size=signal.size,
            price=signal.entry_price,
            stop_loss=signal.stop_loss,
            take_profit=signal.take_profit,
        )
        
        return await self._risk_enforcer.validate_trade(trade_request)
    
    async def _send_for_execution(
        self,
        signal: Signal,
        validation: Any,
    ) -> None:
        """Send a validated signal for execution."""
        adjusted_size = validation.adjusted_size or signal.size
        adjusted_leverage = validation.adjusted_leverage or 1.0
        
        await self.send_message(
            recipient="execution_coordinator",
            message_type="execute_signal",
            payload={
                "signal": {
                    "symbol": signal.symbol,
                    "side": signal.side,
                    "size": adjusted_size,
                    "entry_price": signal.entry_price,
                    "stop_loss": signal.stop_loss,
                    "take_profit": signal.take_profit,
                    "strength": signal.strength,
                    "metadata": signal.metadata,
                },
                "risk_validation": {
                    "decision": validation.decision.value,
                    "warnings": validation.warnings,
                    "adjusted_size": adjusted_size,
                    "adjusted_leverage": adjusted_leverage,
                },
                "timestamp": datetime.utcnow().timestamp(),
            },
            priority=MessagePriority.HIGH,
        )
        
        self.increment_tasks()
    
    async def _analysis_loop(self) -> None:
        """Main analysis loop."""
        while self._state.value != "stopped":
            try:
                # Strategies typically analyze on data updates
                # This loop serves as a fallback/heartbeat
                await asyncio.sleep(10)
            except asyncio.CancelledError:
                break
            except Exception as e:
                self.log_error(f"Analysis loop error: {e}")
                self.increment_errors()
    
    def get_active_signal(self, symbol: str) -> Optional[Signal]:
        """Get the active signal for a symbol."""
        return self._active_signals.get(symbol)
    
    def get_position(self, symbol: str) -> Optional[dict[str, Any]]:
        """Get current position for a symbol."""
        return self._positions.get(symbol)
    
    def set_symbols(self, symbols: list[str]) -> None:
        """Set trading symbols."""
        self._symbols = symbols
