"""
Mean Reversion Scalping Strategy
================================

Scalping strategy based on mean reversion principles using:
- Moving Average (MA)
- Relative Strength Index (RSI)
- Bollinger Bands

Entry when price deviates from mean, exit when it reverts.
"""

import logging
from dataclasses import dataclass
from enum import Enum
from typing import Optional

import numpy as np

logger = logging.getLogger(__name__)


class SignalType(Enum):
    """Trading signal types."""
    BUY = "buy"
    SELL = "sell"
    CLOSE_LONG = "close_long"
    CLOSE_SHORT = "close_short"
    NEUTRAL = "neutral"


@dataclass
class MeanReversionConfig:
    """Configuration for mean reversion strategy."""
    # Indicator periods
    ma_period: int = 20
    rsi_period: int = 14
    bb_period: int = 20
    bb_std: float = 2.0
    
    # Entry/exit thresholds
    deviation_threshold_pct: float = 1.5  # Entry when price deviates this much
    rsi_oversold: float = 30.0  # RSI oversold level
    rsi_overbought: float = 70.0  # RSI overbought level
    bb_lower_entry: float = -1.5  # BB lower band (std devs below mean)
    bb_upper_entry: float = 1.5  # BB upper band (std devs above mean)
    
    # Position sizing (2% risk rule)
    risk_per_trade_pct: float = 2.0  # Maximum risk per trade (%)
    max_position_pct: float = 20.0  # Maximum position size (%)
    
    # Stop loss and take profit
    stop_loss_pct: float = 0.5
    take_profit_pct: float = 0.8
    
    # Confirmation requirements
    require_rsi_confirmation: bool = True
    require_bb_confirmation: bool = False


@dataclass
class MarketData:
    """Market data for analysis."""
    close_prices: list[float]
    high_prices: Optional[list[float]] = None
    low_prices: Optional[list[float]] = None
    volumes: Optional[list[float]] = None
    
    def __post_init__(self):
        if self.high_prices is None:
            self.high_prices = self.close_prices
        if self.low_prices is None:
            self.low_prices = self.close_prices
        if self.volumes is None:
            self.volumes = [1.0] * len(self.close_prices)


@dataclass
class StrategySignal:
    """Signal generated by the strategy."""
    signal_type: SignalType
    confidence: float  # 0-1
    price: float
    deviation_pct: float
    indicators: dict
    timestamp: float
    
    def __str__(self):
        return (
            f"{self.signal_type.value.upper()} @ {self.price:.4f} "
            f"(confidence={self.confidence:.0%}, deviation={self.deviation_pct:.2f}%)"
        )


class MeanReversionStrategy:
    """
    Mean reversion scalping strategy.
    
    Entry Conditions:
    - Price deviates from MA by more than deviation_threshold_pct
    - RSI confirms oversold (< 30) for BUY or overbought (> 70) for SELL
    - Optionally confirmed by Bollinger Bands
    
    Exit Conditions:
    - Price reverts back to MA
    - Stop loss triggered
    - Take profit triggered
    """
    
    def __init__(
        self,
        config: Optional[MeanReversionConfig] = None,
        pair: str = "BTC/USDT",
        exchange: str = "binance",
    ):
        """
        Initialize mean reversion strategy.
        
        Args:
            config: Strategy configuration
            pair: Trading pair
            exchange: Exchange name
        """
        self.config = config or MeanReversionConfig()
        self.pair = pair
        self.exchange = exchange
        self._position_open = False
        self._position_side: Optional[str] = None
        
        logger.info(
            f"Initialized MeanReversionStrategy for {pair} on {exchange}, "
            f"config={self.config}"
        )
    
    def validate_config(self) -> tuple[bool, str]:
        """
        Validate strategy configuration.
        
        Returns:
            Tuple of (is_valid, error_message)
        """
        if self.config.ma_period < 2:
            return False, f"MA period must be >= 2, got {self.config.ma_period}"
        if self.config.rsi_period < 2:
            return False, f"RSI period must be >= 2, got {self.config.rsi_period}"
        if self.config.deviation_threshold_pct <= 0:
            return False, f"Deviation threshold must be > 0"
        if not 0 < self.config.risk_per_trade_pct <= 100:
            return False, f"Risk per trade must be 0-100%"
        if self.config.stop_loss_pct <= 0 or self.config.take_profit_pct <= 0:
            return False, "Stop loss and take profit must be > 0"
        
        return True, "Valid"
    
    def get_signal(self, market_data: MarketData) -> StrategySignal:
        """
        Generate trading signal based on market data.
        
        Args:
            market_data: Recent price and volume data
            
        Returns:
            StrategySignal with entry/exit recommendation
        """
        logger.debug(f"Getting signal for {self.pair} with {len(market_data.close_prices)} candles")
        
        # Ensure we have enough data
        required_periods = max(
            self.config.ma_period,
            self.config.rsi_period,
            self.config.bb_period,
        )
        
        if len(market_data.close_prices) < required_periods:
            logger.warning(
                f"Insufficient data: {len(market_data.close_prices)} < {required_periods}"
            )
            return StrategySignal(
                signal_type=SignalType.NEUTRAL,
                confidence=0.0,
                price=market_data.close_prices[-1],
                deviation_pct=0.0,
                indicators={},
                timestamp=0.0,
            )
        
        # Calculate indicators
        indicators = self._calculate_indicators(market_data)
        
        # Get current values
        current_price = market_data.close_prices[-1]
        ma_value = indicators["ma"][-1]
        rsi_value = indicators["rsi"][-1]
        bb_lower = indicators["bb_lower"][-1]
        bb_upper = indicators["bb_upper"][-1]
        bb_middle = indicators["bb_middle"][-1]
        
        # Calculate deviation from MA
        deviation_pct = ((current_price - ma_value) / ma_value) * 100
        
        # Determine signal
        signal_type = SignalType.NEUTRAL
        confidence = 0.0
        
        # Buy signal: price below MA by threshold (oversold)
        if deviation_pct < -self.config.deviation_threshold_pct:
            # Check RSI confirmation
            if self.config.require_rsi_confirmation:
                if rsi_value < self.config.rsi_oversold:
                    signal_type = SignalType.BUY
                    confidence = self._calculate_buy_confidence(
                        deviation_pct, rsi_value, bb_lower, current_price
                    )
                else:
                    signal_type = SignalType.NEUTRAL
            else:
                signal_type = SignalType.BUY
                confidence = self._calculate_buy_confidence(
                    deviation_pct, rsi_value, bb_lower, current_price
                )
        
        # Sell signal: price above MA by threshold (overbought)
        elif deviation_pct > self.config.deviation_threshold_pct:
            if self.config.require_rsi_confirmation:
                if rsi_value > self.config.rsi_overbought:
                    signal_type = SignalType.SELL
                    confidence = self._calculate_sell_confidence(
                        deviation_pct, rsi_value, bb_upper, current_price
                    )
                else:
                    signal_type = SignalType.NEUTRAL
            else:
                signal_type = SignalType.SELL
                confidence = self._calculate_sell_confidence(
                    deviation_pct, rsi_value, bb_upper, current_price
                )
        
        # Close signals (reversion to mean)
        elif self._position_open:
            if self._position_side == "long" and deviation_pct >= -self.config.deviation_threshold_pct * 0.5:
                signal_type = SignalType.CLOSE_LONG
                confidence = 0.7
            elif self._position_side == "short" and deviation_pct <= self.config.deviation_threshold_pct * 0.5:
                signal_type = SignalType.CLOSE_SHORT
                confidence = 0.7
        
        logger.info(
            f"Signal for {self.pair}: {signal_type.value}, "
            f"price={current_price:.4f}, deviation={deviation_pct:.2f}%, "
            f"rsi={rsi_value:.1f}, confidence={confidence:.0%}"
        )
        
        return StrategySignal(
            signal_type=signal_type,
            confidence=confidence,
            price=current_price,
            deviation_pct=deviation_pct,
            indicators=indicators,
            timestamp=0.0,  # Would be actual timestamp in real implementation
        )
    
    def _calculate_indicators(self, market_data: MarketData) -> dict:
        """Calculate all technical indicators."""
        closes = np.array(market_data.close_prices)
        
        # Simple Moving Average
        ma = self._sma(closes, self.config.ma_period)
        
        # RSI
        rsi = self._rsi(closes, self.config.rsi_period)
        
        # Bollinger Bands
        bb_middle, bb_upper, bb_lower = self._bollinger_bands(
            closes,
            self.config.bb_period,
            self.config.bb_std,
        )
        
        return {
            "ma": ma,
            "rsi": rsi,
            "bb_middle": bb_middle,
            "bb_upper": bb_upper,
            "bb_lower": bb_lower,
        }
    
    def _sma(self, data: np.ndarray, period: int) -> np.ndarray:
        """Calculate Simple Moving Average."""
        result = np.full(len(data), np.nan)
        for i in range(period - 1, len(data)):
            result[i] = np.mean(data[i - period + 1:i + 1])
        return result
    
    def _rsi(self, data: np.ndarray, period: int) -> np.ndarray:
        """Calculate Relative Strength Index."""
        result = np.full(len(data), np.nan)
        
        if len(data) < period + 1:
            return result
        
        deltas = np.diff(data)
        gains = np.where(deltas > 0, deltas, 0)
        losses = np.where(deltas < 0, -deltas, 0)
        
        avg_gain = np.mean(gains[:period])
        avg_loss = np.mean(losses[:period])
        
        if avg_loss == 0:
            result[period] = 100
        else:
            rs = avg_gain / avg_loss
            result[period] = 100 - (100 / (1 + rs))
        
        for i in range(period, len(data) - 1):
            avg_gain = (avg_gain * (period - 1) + gains[i]) / period
            avg_loss = (avg_loss * (period - 1) + losses[i]) / period
            
            if avg_loss == 0:
                result[i + 1] = 100
            else:
                rs = avg_gain / avg_loss
                result[i + 1] = 100 - (100 / (1 + rs))
        
        return result
    
    def _bollinger_bands(
        self,
        data: np.ndarray,
        period: int,
        std_dev: float,
    ) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
        """Calculate Bollinger Bands."""
        middle = self._sma(data, period)
        
        # Calculate standard deviation
        std = np.full(len(data), np.nan)
        for i in range(period - 1, len(data)):
            std[i] = np.std(data[i - period + 1:i + 1])
        
        upper = middle + (std * std_dev)
        lower = middle - (std * std_dev)
        
        return middle, upper, lower
    
    def _calculate_buy_confidence(
        self,
        deviation_pct: float,
        rsi_value: float,
        bb_lower: float,
        current_price: float,
    ) -> float:
        """Calculate confidence for a BUY signal."""
        confidence = 0.5  # Base confidence
        
        # More deviation = higher confidence
        deviation_factor = min(abs(deviation_pct) / 3.0, 1.0)
        confidence += deviation_factor * 0.2
        
        # RSI confirmation
        if rsi_value < 30:
            confidence += 0.15
        elif rsi_value < 40:
            confidence += 0.1
        
        # BB confirmation
        if current_price <= bb_lower:
            confidence += 0.1
        
        return min(confidence, 0.95)  # Cap at 95%
    
    def _calculate_sell_confidence(
        self,
        deviation_pct: float,
        rsi_value: float,
        bb_upper: float,
        current_price: float,
    ) -> float:
        """Calculate confidence for a SELL signal."""
        confidence = 0.5  # Base confidence
        
        # More deviation = higher confidence
        deviation_factor = min(abs(deviation_pct) / 3.0, 1.0)
        confidence += deviation_factor * 0.2
        
        # RSI confirmation
        if rsi_value > 70:
            confidence += 0.15
        elif rsi_value > 60:
            confidence += 0.1
        
        # BB confirmation
        if current_price >= bb_upper:
            confidence += 0.1
        
        return min(confidence, 0.95)  # Cap at 95%
    
    def calculate_position_size(
        self,
        capital_usd: float,
        entry_price: float,
        stop_loss_price: float,
    ) -> float:
        """
        Calculate position size using 2% risk rule.
        
        Args:
            capital_usd: Total trading capital in USD
            entry_price: Planned entry price
            stop_loss_price: Stop loss price
            
        Returns:
            Position size in base currency
        """
        # Calculate risk amount (2% of capital)
        risk_amount = capital_usd * (self.config.risk_per_trade_pct / 100)
        
        # Calculate stop loss distance
        stop_distance_pct = abs((entry_price - stop_loss_price) / entry_price) * 100
        
        if stop_distance_pct == 0:
            logger.warning("Stop loss distance is 0, using minimum position")
            return capital_usd * 0.01 / entry_price
        
        # Position size = risk / stop distance
        position_value = risk_amount / (stop_distance_pct / 100)
        
        # Apply maximum position limit
        max_position_value = capital_usd * (self.config.max_position_pct / 100)
        position_value = min(position_value, max_position_value)
        
        # Convert to base currency
        position_size = position_value / entry_price
        
        logger.info(
            f"Position size: {position_size:.4f} (value=${position_value:.2f}, "
            f"risk=${risk_amount:.2f}, stop_dist={stop_distance_pct:.2f}%)"
        )
        
        return position_size
    
    def calculate_stop_loss(
        self,
        entry_price: float,
        signal_type: SignalType,
    ) -> float:
        """
        Calculate stop loss price.
        
        Args:
            entry_price: Entry price
            signal_type: BUY or SELL
            
        Returns:
            Stop loss price
        """
        if signal_type == SignalType.BUY:
            return entry_price * (1 - self.config.stop_loss_pct / 100)
        else:
            return entry_price * (1 + self.config.stop_loss_pct / 100)
    
    def calculate_take_profit(
        self,
        entry_price: float,
        signal_type: SignalType,
    ) -> float:
        """
        Calculate take profit price.
        
        Args:
            entry_price: Entry price
            signal_type: BUY or SELL
            
        Returns:
            Take profit price
        """
        if signal_type == SignalType.BUY:
            return entry_price * (1 + self.config.take_profit_pct / 100)
        else:
            return entry_price * (1 - self.config.take_profit_pct / 100)
    
    def update_position_state(self, signal: StrategySignal):
        """Update internal position state based on signals."""
        if signal.signal_type == SignalType.BUY:
            self._position_open = True
            self._position_side = "long"
        elif signal.signal_type == SignalType.SELL:
            self._position_open = True
            self._position_side = "short"
        elif signal.signal_type in [SignalType.CLOSE_LONG, SignalType.CLOSE_SHORT]:
            self._position_open = False
            self._position_side = None
