"""
Momentum Scalping Strategy
==========================

Scalping strategy based on momentum/breakout principles using:
- Exponential Moving Averages (EMA)
- Volume spike detection
- Trend confirmation signals

Entry when momentum confirms trend direction, exit with trailing stop.
"""

import logging
from dataclasses import dataclass
from enum import Enum
from typing import Optional

import numpy as np

logger = logging.getLogger(__name__)


class SignalType(Enum):
    """Trading signal types."""
    BUY = "buy"
    SELL = "sell"
    CLOSE_LONG = "close_long"
    CLOSE_SHORT = "close_short"
    NEUTRAL = "neutral"


@dataclass
class MomentumConfig:
    """Configuration for momentum strategy."""
    # EMA periods
    ema_fast: int = 9
    ema_slow: int = 21
    ema_trend: int = 50  # For trend confirmation
    
    # Volume settings
    volume_ma_period: int = 20
    volume_threshold: float = 1.5  # Volume must be this multiple of MA
    
    # Entry parameters
    min_ema_spacing_pct: float = 0.3  # Minimum EMA separation for valid signal
    
    # Stop loss and take profit
    stop_loss_pct: float = 0.8
    take_profit_pct: float = 1.5
    trailing_stop_pct: float = 0.3  # Trailing stop activation
    
    # Trend confirmation
    require_trend_confirmation: bool = True
    trend_ema_period: int = 50
    
    # Position sizing
    max_position_pct: float = 20.0
    risk_per_trade_pct: float = 2.0


@dataclass
class MarketData:
    """Market data for analysis."""
    close_prices: list[float]
    high_prices: Optional[list[float]] = None
    low_prices: Optional[list[float]] = None
    volumes: Optional[list[float]] = None
    
    def __post_init__(self):
        if self.high_prices is None:
            self.high_prices = self.close_prices
        if self.low_prices is None:
            self.low_prices = self.close_prices
        if self.volumes is None:
            self.volumes = [1.0] * len(self.close_prices)


@dataclass
class StrategySignal:
    """Signal generated by the strategy."""
    signal_type: SignalType
    confidence: float  # 0-1
    price: float
    ema_cross_value: float
    volume_ratio: float
    indicators: dict
    timestamp: float
    
    def __str__(self):
        return (
            f"{self.signal_type.value.upper()} @ {self.price:.4f} "
            f"(confidence={self.confidence:.0%}, vol_ratio={self.volume_ratio:.1f}x)"
        )


class MomentumStrategy:
    """
    Momentum breakout scalping strategy.
    
    Entry Conditions:
    - EMA(9) crosses above EMA(21) for BUY (golden cross)
    - EMA(9) crosses below EMA(21) for SELL (death cross)
    - Volume spike confirms the breakout
    - Optional: trend EMA confirms direction
    
    Exit Conditions:
    - Trailing stop triggered
    - Take profit reached
    - Opposite signal generated
    """
    
    def __init__(
        self,
        config: Optional[MomentumConfig] = None,
        pair: str = "BTC/USDT",
        exchange: str = "binance",
    ):
        """
        Initialize momentum strategy.
        
        Args:
            config: Strategy configuration
            pair: Trading pair
            exchange: Exchange name
        """
        self.config = config or MomentumConfig()
        self.pair = pair
        self.exchange = exchange
        self._position_open = False
        self._position_side: Optional[str] = None
        self._highest_price_since_entry: float = 0.0
        self._lowest_price_since_entry: float = float('inf')
        
        logger.info(
            f"Initialized MomentumStrategy for {pair} on {exchange}, "
            f"config={self.config}"
        )
    
    def validate_config(self) -> tuple[bool, str]:
        """
        Validate strategy configuration.
        
        Returns:
            Tuple of (is_valid, error_message)
        """
        if self.config.ema_fast >= self.config.ema_slow:
            return False, f"EMA fast ({self.config.ema_fast}) must be < EMA slow ({self.config.ema_slow})"
        if self.config.ema_fast < 2:
            return False, f"EMA fast must be >= 2, got {self.config.ema_fast}"
        if self.config.volume_threshold <= 0:
            return False, f"Volume threshold must be > 0"
        if self.config.trailing_stop_pct <= 0:
            return False, f"Trailing stop must be > 0"
        if self.config.stop_loss_pct <= 0 or self.config.take_profit_pct <= 0:
            return False, "Stop loss and take profit must be > 0"
        
        return True, "Valid"
    
    def get_signal(self, market_data: MarketData) -> StrategySignal:
        """
        Generate trading signal based on market data.
        
        Args:
            market_data: Recent price and volume data
            
        Returns:
            StrategySignal with entry/exit recommendation
        """
        logger.debug(f"Getting signal for {self.pair} with {len(market_data.close_prices)} candles")
        
        # Ensure we have enough data
        required_periods = max(
            self.config.ema_slow,
            self.config.volume_ma_period,
            self.config.trend_ema_period,
        ) + 2  # Need extra for crossover detection
        
        if len(market_data.close_prices) < required_periods:
            logger.warning(
                f"Insufficient data: {len(market_data.close_prices)} < {required_periods}"
            )
            return StrategySignal(
                signal_type=SignalType.NEUTRAL,
                confidence=0.0,
                price=market_data.close_prices[-1],
                ema_cross_value=0.0,
                volume_ratio=1.0,
                indicators={},
                timestamp=0.0,
            )
        
        # Calculate indicators
        indicators = self._calculate_indicators(market_data)
        
        # Get current values
        current_price = market_data.close_prices[-1]
        ema_fast = indicators["ema_fast"]
        ema_slow = indicators["ema_slow"]
        ema_fast_prev = ema_fast[-2]
        ema_slow_prev = ema_slow[-2]
        volume_ratio = indicators["volume_ratio"][-1]
        trend_ema = indicators.get("trend_ema", [0])[-1]
        
        # Detect crossover
        ema_cross_prev = ema_fast_prev - ema_slow_prev
        ema_cross_current = ema_fast[-1] - ema_slow[-1]
        
        # Determine signal
        signal_type = SignalType.NEUTRAL
        confidence = 0.0
        
        # Check for golden cross (BUY)
        if ema_cross_prev <= 0 and ema_cross_current > 0:
            # Check volume confirmation
            if volume_ratio >= self.config.volume_threshold:
                # Check trend confirmation if required
                if self.config.require_trend_confirmation:
                    if current_price > trend_ema:
                        signal_type = SignalType.BUY
                        confidence = self._calculate_buy_confidence(
                            volume_ratio, ema_cross_current, current_price, trend_ema
                        )
                else:
                    signal_type = SignalType.BUY
                    confidence = self._calculate_buy_confidence(
                        volume_ratio, ema_cross_current, current_price, trend_ema
                    )
        
        # Check for death cross (SELL)
        elif ema_cross_prev >= 0 and ema_cross_current < 0:
            if volume_ratio >= self.config.volume_threshold:
                if self.config.require_trend_confirmation:
                    if current_price < trend_ema:
                        signal_type = SignalType.SELL
                        confidence = self._calculate_sell_confidence(
                            volume_ratio, abs(ema_cross_current), current_price, trend_ema
                        )
                else:
                    signal_type = SignalType.SELL
                    confidence = self._calculate_sell_confidence(
                        volume_ratio, abs(ema_cross_current), current_price, trend_ema
                    )
        
        # Check for close signals if position is open
        if self._position_open:
            close_signal = self._check_close_conditions(current_price)
            if close_signal:
                signal_type = close_signal
                confidence = 0.8
        
        logger.info(
            f"Signal for {self.pair}: {signal_type.value}, "
            f"price={current_price:.4f}, volume_ratio={volume_ratio:.1f}x, "
            f"confidence={confidence:.0%}"
        )
        
        return StrategySignal(
            signal_type=signal_type,
            confidence=confidence,
            price=current_price,
            ema_cross_value=ema_cross_current,
            volume_ratio=volume_ratio,
            indicators=indicators,
            timestamp=0.0,
        )
    
    def _calculate_indicators(self, market_data: MarketData) -> dict:
        """Calculate all technical indicators."""
        closes = np.array(market_data.close_prices)
        volumes = np.array(market_data.volumes)
        
        # EMA calculations
        ema_fast = self._ema(closes, self.config.ema_fast)
        ema_slow = self._ema(closes, self.config.ema_slow)
        
        # Volume MA and ratio
        volume_ma = self._ema(volumes, self.config.volume_ma_period)
        volume_ratio = volumes / np.where(volume_ma == 0, 1, volume_ma)
        
        result = {
            "ema_fast": ema_fast,
            "ema_slow": ema_slow,
            "volume_ma": volume_ma,
            "volume_ratio": volume_ratio,
        }
        
        # Trend EMA if required
        if self.config.require_trend_confirmation:
            result["trend_ema"] = self._ema(closes, self.config.trend_ema_period)
        
        return result
    
    def _ema(self, data: np.ndarray, period: int) -> np.ndarray:
        """Calculate Exponential Moving Average."""
        result = np.full(len(data), np.nan)
        
        if len(data) < period:
            return result
        
        # Use SMA for first value
        result[period - 1] = np.mean(data[:period])
        
        # Multiplier
        multiplier = 2 / (period + 1)
        
        # Calculate EMA
        for i in range(period, len(data)):
            result[i] = (data[i] - result[i - 1]) * multiplier + result[i - 1]
        
        return result
    
    def _calculate_buy_confidence(
        self,
        volume_ratio: float,
        ema_cross: float,
        current_price: float,
        trend_ema: float,
    ) -> float:
        """Calculate confidence for a BUY signal."""
        confidence = 0.5  # Base confidence
        
        # Volume strength
        vol_factor = min(volume_ratio / 2.0, 1.0)
        confidence += vol_factor * 0.2
        
        # EMA separation strength
        ema_spacing_pct = (ema_cross / current_price) * 100
        spacing_factor = min(ema_spacing_pct / 1.0, 1.0)
        confidence += spacing_factor * 0.15
        
        # Trend alignment bonus
        if trend_ema > 0:
            price_vs_trend = (current_price - trend_ema) / trend_ema * 100
            if price_vs_trend > 0:
                confidence += 0.1
        
        return min(confidence, 0.95)
    
    def _calculate_sell_confidence(
        self,
        volume_ratio: float,
        ema_cross: float,
        current_price: float,
        trend_ema: float,
    ) -> float:
        """Calculate confidence for a SELL signal."""
        confidence = 0.5  # Base confidence
        
        # Volume strength
        vol_factor = min(volume_ratio / 2.0, 1.0)
        confidence += vol_factor * 0.2
        
        # EMA separation strength
        ema_spacing_pct = (ema_cross / current_price) * 100
        spacing_factor = min(ema_spacing_pct / 1.0, 1.0)
        confidence += spacing_factor * 0.15
        
        # Trend alignment bonus
        if trend_ema > 0:
            price_vs_trend = (current_price - trend_ema) / trend_ema * 100
            if price_vs_trend < 0:
                confidence += 0.1
        
        return min(confidence, 0.95)
    
    def _check_close_conditions(self, current_price: float) -> Optional[SignalType]:
        """
        Check if position should be closed based on trailing stop or signals.
        
        Args:
            current_price: Current market price
            
        Returns:
            Close signal type or None
        """
        if not self._position_open:
            return None
        
        if self._position_side == "long":
            # Update highest price
            if current_price > self._highest_price_since_entry:
                self._highest_price_since_entry = current_price
            
            # Check trailing stop
            trailing_stop_price = self._highest_price_since_entry * (
                1 - self.config.trailing_stop_pct / 100
            )
            
            if current_price <= trailing_stop_price:
                logger.info(f"Trailing stop triggered: {current_price:.4f} <= {trailing_stop_price:.4f}")
                return SignalType.CLOSE_LONG
            
            # Check for death cross
            # This would be handled by get_signal returning SELL
        
        elif self._position_side == "short":
            # Update lowest price
            if current_price < self._lowest_price_since_entry:
                self._lowest_price_since_entry = current_price
            
            # Check trailing stop
            trailing_stop_price = self._lowest_price_since_entry * (
                1 + self.config.trailing_stop_pct / 100
            )
            
            if current_price >= trailing_stop_price:
                logger.info(f"Trailing stop triggered: {current_price:.4f} >= {trailing_stop_price:.4f}")
                return SignalType.CLOSE_SHORT
        
        return None
    
    def update_position_state(self, signal: StrategySignal, entry_price: float):
        """
        Update internal position state based on signals.
        
        Args:
            signal: The signal that opened/modified the position
            entry_price: The entry price of the position
        """
        if signal.signal_type == SignalType.BUY:
            self._position_open = True
            self._position_side = "long"
            self._highest_price_since_entry = entry_price
            self._lowest_price_since_entry = float('inf')
        elif signal.signal_type == SignalType.SELL:
            self._position_open = True
            self._position_side = "short"
            self._highest_price_since_entry = 0.0
            self._lowest_price_since_entry = entry_price
        elif signal.signal_type in [SignalType.CLOSE_LONG, SignalType.CLOSE_SHORT]:
            self._position_open = False
            self._position_side = None
            self._highest_price_since_entry = 0.0
            self._lowest_price_since_entry = float('inf')
    
    def calculate_position_size(
        self,
        capital_usd: float,
        entry_price: float,
        stop_loss_price: float,
    ) -> float:
        """
        Calculate position size using 2% risk rule.
        
        Args:
            capital_usd: Total trading capital in USD
            entry_price: Planned entry price
            stop_loss_price: Stop loss price
            
        Returns:
            Position size in base currency
        """
        # Calculate risk amount (2% of capital)
        risk_amount = capital_usd * (self.config.risk_per_trade_pct / 100)
        
        # Calculate stop loss distance
        stop_distance_pct = abs((entry_price - stop_loss_price) / entry_price) * 100
        
        if stop_distance_pct == 0:
            logger.warning("Stop loss distance is 0, using minimum position")
            return capital_usd * 0.01 / entry_price
        
        # Position size = risk / stop distance
        position_value = risk_amount / (stop_distance_pct / 100)
        
        # Apply maximum position limit
        max_position_value = capital_usd * (self.config.max_position_pct / 100)
        position_value = min(position_value, max_position_value)
        
        # Convert to base currency
        position_size = position_value / entry_price
        
        logger.info(
            f"Position size: {position_size:.4f} (value=${position_value:.2f}, "
            f"risk=${risk_amount:.2f}, stop_dist={stop_distance_pct:.2f}%)"
        )
        
        return position_size
    
    def calculate_stop_loss(
        self,
        entry_price: float,
        signal_type: SignalType,
    ) -> float:
        """
        Calculate stop loss price.
        
        Args:
            entry_price: Entry price
            signal_type: BUY or SELL
            
        Returns:
            Stop loss price
        """
        if signal_type == SignalType.BUY:
            return entry_price * (1 - self.config.stop_loss_pct / 100)
        else:
            return entry_price * (1 + self.config.stop_loss_pct / 100)
    
    def calculate_take_profit(
        self,
        entry_price: float,
        signal_type: SignalType,
    ) -> float:
        """
        Calculate take profit price.
        
        Args:
            entry_price: Entry price
            signal_type: BUY or SELL
            
        Returns:
            Take profit price
        """
        if signal_type == SignalType.BUY:
            return entry_price * (1 + self.config.take_profit_pct / 100)
        else:
            return entry_price * (1 - self.config.take_profit_pct / 100)
    
    def get_trailing_stop_price(self, current_price: float) -> float:
        """
        Calculate current trailing stop price.
        
        Args:
            current_price: Current market price
            
        Returns:
            Trailing stop price
        """
        if not self._position_open:
            return 0.0
        
        if self._position_side == "long":
            trailing_stop = self._highest_price_since_entry * (
                1 - self.config.trailing_stop_pct / 100
            )
        else:
            trailing_stop = self._lowest_price_since_entry * (
                1 + self.config.trailing_stop_pct / 100
            )
        
        return trailing_stop
