"""
Momentum Trend Following Strategy
=================================

Trend following strategy using:
- EMA crossover (50/200)
- ADX trend strength filter
- 4H timeframe analysis

Enters on trend confirmation, exits on trend reversal or stop loss.
"""

import logging
from dataclasses import dataclass
from enum import Enum
from typing import Optional

import numpy as np

logger = logging.getLogger(__name__)


class SignalType(Enum):
    """Trading signal types."""
    BUY = "buy"
    SELL = "sell"
    CLOSE_LONG = "close_long"
    CLOSE_SHORT = "close_short"
    NEUTRAL = "neutral"


class TrendStrength(Enum):
    """ADX trend strength classification."""
    WEAK = "weak"  # ADX < 25
    MODERATE = "moderate"  # 25 <= ADX < 50
    STRONG = "strong"  # ADX >= 50
    VERY_STRONG = "very_strong"  # ADX >= 75


@dataclass
class TrendFollowerConfig:
    """Configuration for trend following strategy."""
    # EMA periods
    ema_fast: int = 50  # Default fast EMA
    ema_slow: int = 200  # Default slow EMA
    
    # ADX settings
    adx_period: int = 14
    adx_threshold: float = 25.0  # Minimum ADX for valid trend
    
    # Timeframe
    timeframe: str = "4h"
    
    # Entry parameters
    min_crossover_distance_pct: float = 0.5  # Minimum EMA separation
    
    # Stop loss and take profit
    stop_loss_pct: float = 3.0
    take_profit_pct: float = 8.0  # Can be overridden per trade
    
    # Position sizing
    max_position_pct: float = 30.0
    risk_per_trade_pct: float = 2.0
    
    # Trend confirmation
    require_adx_confirmation: bool = True
    min_trend_duration_bars: int = 2  # Confirm trend after N bars


@dataclass
class MarketData:
    """Market data for analysis."""
    close_prices: list[float]
    high_prices: list[float]
    low_prices: list[float]
    volumes: Optional[list[float]] = None
    
    def __post_init__(self):
        if self.volumes is None:
            self.volumes = [1.0] * len(self.close_prices)


@dataclass
class StrategySignal:
    """Signal generated by the strategy."""
    signal_type: SignalType
    confidence: float  # 0-1
    price: float
    trend: str  # "bullish", "bearish", "neutral"
    adx_value: float
    adx_strength: TrendStrength
    indicators: dict
    timestamp: float
    
    def __str__(self):
        return (
            f"{self.signal_type.value.upper()} @ {self.price:.4f} "
            f"(trend={self.trend}, ADX={self.adx_value:.1f}, "
            f"confidence={self.confidence:.0%})"
        )


class TrendFollowerStrategy:
    """
    Trend following strategy with ADX filter.
    
    Entry Conditions:
    - EMA(50) crosses above EMA(200) for BUY (golden cross)
    - EMA(50) crosses below EMA(200) for SELL (death cross)
    - ADX must be above threshold (25) to confirm trend strength
    - Price must be above/below both EMAs for trend direction
    
    Exit Conditions:
    - Opposite crossover occurs
    - Stop loss triggered
    - Take profit reached
    - ADX drops below threshold (trend weakening)
    """
    
    def __init__(
        self,
        config: Optional[TrendFollowerConfig] = None,
        pair: str = "BTC/USDT",
        exchange: str = "binance",
    ):
        """
        Initialize trend follower strategy.
        
        Args:
            config: Strategy configuration
            pair: Trading pair
            exchange: Exchange name
        """
        self.config = config or TrendFollowerConfig()
        self.pair = pair
        self.exchange = exchange
        self._position_open = False
        self._position_side: Optional[str] = None
        self._trend_bars_count = 0  # Bars since trend confirmation
        self._entry_price: float = 0.0
        
        logger.info(
            f"Initialized TrendFollowerStrategy for {pair} on {exchange}, "
            f"EMA({self.config.ema_fast}/{self.config.ema_slow}), "
            f"ADX threshold={self.config.adx_threshold}"
        )
    
    def validate_config(self) -> tuple[bool, str]:
        """
        Validate strategy configuration.
        
        Returns:
            Tuple of (is_valid, error_message)
        """
        if self.config.ema_fast >= self.config.ema_slow:
            return False, f"EMA fast ({self.config.ema_fast}) must be < EMA slow ({self.config.ema_slow})"
        if self.config.ema_fast < 2:
            return False, f"EMA fast must be >= 2"
        if self.config.adx_threshold <= 0:
            return False, f"ADX threshold must be > 0"
        if self.config.adx_period < 1:
            return False, f"ADX period must be >= 1"
        if self.config.stop_loss_pct <= 0 or self.config.take_profit_pct <= 0:
            return False, "Stop loss and take profit must be > 0"
        
        return True, "Valid"
    
    def get_signal(self, market_data: MarketData) -> StrategySignal:
        """
        Generate trading signal based on market data.
        
        Args:
            market_data: Recent price and volume data
            
        Returns:
            StrategySignal with entry/exit recommendation
        """
        logger.debug(f"Getting signal for {self.pair} with {len(market_data.close_prices)} candles")
        
        # Ensure we have enough data
        required_periods = max(
            self.config.ema_slow,
            self.config.adx_period,
        ) + 5
        
        if len(market_data.close_prices) < required_periods:
            logger.warning(
                f"Insufficient data: {len(market_data.close_prices)} < {required_periods}"
            )
            return StrategySignal(
                signal_type=SignalType.NEUTRAL,
                confidence=0.0,
                price=market_data.close_prices[-1],
                trend="neutral",
                adx_value=0.0,
                adx_strength=TrendStrength.WEAK,
                indicators={},
                timestamp=0.0,
            )
        
        # Calculate indicators
        indicators = self._calculate_indicators(market_data)
        
        # Get current values
        current_price = market_data.close_prices[-1]
        ema_fast = indicators["ema_fast"][-1]
        ema_slow = indicators["ema_slow"][-1]
        adx = indicators["adx"][-1]
        plus_di = indicators["plus_di"][-1]
        minus_di = indicators["minus_di"][-1]
        
        # Previous values for crossover detection
        ema_fast_prev = indicators["ema_fast"][-2]
        ema_slow_prev = indicators["ema_slow"][-2]
        
        # Determine trend direction
        if plus_di > minus_di and ema_fast > ema_slow:
            trend = "bullish"
        elif plus_di < minus_di and ema_fast < ema_slow:
            trend = "bearish"
        else:
            trend = "neutral"
        
        # Determine ADX strength
        if adx < 25:
            adx_strength = TrendStrength.WEAK
        elif adx < 50:
            adx_strength = TrendStrength.MODERATE
        elif adx < 75:
            adx_strength = TrendStrength.STRONG
        else:
            adx_strength = TrendStrength.VERY_STRONG
        
        # Detect crossover
        crossover_prev = ema_fast_prev - ema_slow_prev
        crossover_current = ema_fast - ema_slow
        
        # Determine signal
        signal_type = SignalType.NEUTRAL
        confidence = 0.0
        
        # Golden cross (BUY)
        if crossover_prev <= 0 and crossover_current > 0:
            # Check ADX confirmation
            if self.config.require_adx_confirmation:
                if adx >= self.config.adx_threshold:
                    signal_type = SignalType.BUY
                    confidence = self._calculate_buy_confidence(
                        adx, adx_strength, crossover_current, current_price, ema_fast
                    )
                    self._trend_bars_count = 1
            else:
                signal_type = SignalType.BUY
                confidence = self._calculate_buy_confidence(
                    adx, adx_strength, crossover_current, current_price, ema_fast
                )
                self._trend_bars_count = 1
        
        # Death cross (SELL)
        elif crossover_prev >= 0 and crossover_current < 0:
            if self.config.require_adx_confirmation:
                if adx >= self.config.adx_threshold:
                    signal_type = SignalType.SELL
                    confidence = self._calculate_sell_confidence(
                        adx, adx_strength, abs(crossover_current), current_price, ema_fast
                    )
                    self._trend_bars_count = 1
            else:
                signal_type = SignalType.SELL
                confidence = self._calculate_sell_confidence(
                    adx, adx_strength, abs(crossover_current), current_price, ema_fast
                )
                self._trend_bars_count = 1
        
        # Check for close signals if position is open
        if self._position_open:
            close_signal = self._check_close_conditions(
                current_price, trend, adx, adx_strength
            )
            if close_signal:
                signal_type = close_signal
                confidence = 0.85
        else:
            # Reset trend counter if no position
            self._trend_bars_count = 0
        
        logger.info(
            f"Signal for {self.pair}: {signal_type.value}, "
            f"trend={trend}, ADX={adx:.1f} ({adx_strength.value}), "
            f"price={current_price:.4f}, confidence={confidence:.0%}"
        )
        
        return StrategySignal(
            signal_type=signal_type,
            confidence=confidence,
            price=current_price,
            trend=trend,
            adx_value=adx,
            adx_strength=adx_strength,
            indicators=indicators,
            timestamp=0.0,
        )
    
    def _calculate_indicators(self, market_data: MarketData) -> dict:
        """Calculate all technical indicators."""
        closes = np.array(market_data.close_prices)
        highs = np.array(market_data.high_prices)
        lows = np.array(market_data.low_prices)
        
        # EMA calculations
        ema_fast = self._ema(closes, self.config.ema_fast)
        ema_slow = self._ema(closes, self.config.ema_slow)
        
        # ADX calculation
        adx, plus_di, minus_di = self._adx(highs, lows, closes, self.config.adx_period)
        
        return {
            "ema_fast": ema_fast,
            "ema_slow": ema_slow,
            "adx": adx,
            "plus_di": plus_di,
            "minus_di": minus_di,
        }
    
    def _ema(self, data: np.ndarray, period: int) -> np.ndarray:
        """Calculate Exponential Moving Average."""
        result = np.full(len(data), np.nan)
        
        if len(data) < period:
            return result
        
        # Use SMA for first value
        result[period - 1] = np.mean(data[:period])
        
        # Multiplier
        multiplier = 2 / (period + 1)
        
        # Calculate EMA
        for i in range(period, len(data)):
            result[i] = (data[i] - result[i - 1]) * multiplier + result[i - 1]
        
        return result
    
    def _adx(
        self,
        highs: np.ndarray,
        lows: np.ndarray,
        closes: np.ndarray,
        period: int,
    ) -> tuple:
        """
        Calculate ADX, +DI, -DI.
        
        Returns:
            Tuple of (adx, plus_di, minus_di) arrays
        """
        n = len(closes)
        
        # True Range
        tr = np.zeros(n - 1)
        plus_dm = np.zeros(n - 1)
        minus_dm = np.zeros(n - 1)
        
        for i in range(1, n):
            high_low = highs[i] - lows[i]
            high_close = abs(highs[i] - closes[i - 1])
            low_close = abs(lows[i] - closes[i - 1])
            
            tr[i - 1] = max(high_low, high_close, low_close)
            
            up_move = highs[i] - highs[i - 1]
            down_move = lows[i - 1] - lows[i]
            
            if up_move > down_move and up_move > 0:
                plus_dm[i - 1] = up_move
            if down_move > up_move and down_move > 0:
                minus_dm[i - 1] = down_move
        
        # Smooth values
        period = min(period, len(tr))
        if period < 1:
            period = 14
        
        tr_smooth = np.full(n, np.nan)
        plus_dm_smooth = np.full(n, np.nan)
        minus_dm_smooth = np.full(n, np.nan)
        
        tr_smooth[period] = np.sum(tr[:period])
        plus_dm_smooth[period] = np.sum(plus_dm[:period])
        minus_dm_smooth[period] = np.sum(minus_dm[:period])
        
        for i in range(period + 1, n):
            tr_smooth[i] = tr_smooth[i - 1] - (tr_smooth[i - 1] / period) + tr[i - 1]
            plus_dm_smooth[i] = plus_dm_smooth[i - 1] - (plus_dm_smooth[i - 1] / period) + plus_dm[i - 1]
            minus_dm_smooth[i] = minus_dm_smooth[i - 1] - (minus_dm_smooth[i - 1] / period) + minus_dm[i - 1]
        
        # Calculate DI
        plus_di = np.zeros(n)
        minus_di = np.zeros(n)
        
        for i in range(period, n):
            if tr_smooth[i] != 0:
                plus_di[i] = (plus_dm_smooth[i] / tr_smooth[i]) * 100
                minus_di[i] = (minus_dm_smooth[i] / tr_smooth[i]) * 100
        
        # Calculate DX
        dx = np.zeros(n)
        for i in range(period, n):
            di_sum = plus_di[i] + minus_di[i]
            if di_sum != 0:
                dx[i] = (abs(plus_di[i] - minus_di[i]) / di_sum) * 100
        
        # Calculate ADX (smoothed DX)
        adx = np.full(n, np.nan)
        adx[period * 2] = np.mean(dx[period:period * 2])
        
        for i in range(period * 2 + 1, n):
            adx[i] = ((adx[i - 1] * (period - 1)) + dx[i]) / period
        
        return adx, plus_di, minus_di
    
    def _calculate_buy_confidence(
        self,
        adx: float,
        adx_strength: TrendStrength,
        crossover_value: float,
        current_price: float,
        ema_fast: float,
    ) -> float:
        """Calculate confidence for a BUY signal."""
        confidence = 0.5  # Base confidence
        
        # ADX strength contribution
        if adx_strength == TrendStrength.VERY_STRONG:
            confidence += 0.25
        elif adx_strength == TrendStrength.STRONG:
            confidence += 0.2
        elif adx_strength == TrendStrength.MODERATE:
            confidence += 0.1
        
        # Crossover distance
        crossover_pct = (crossover_value / current_price) * 100
        crossover_factor = min(crossover_pct / 1.0, 1.0)
        confidence += crossover_factor * 0.15
        
        # Price above EMA confirmation
        if current_price > ema_fast:
            confidence += 0.1
        
        return min(confidence, 0.95)
    
    def _calculate_sell_confidence(
        self,
        adx: float,
        adx_strength: TrendStrength,
        crossover_value: float,
        current_price: float,
        ema_fast: float,
    ) -> float:
        """Calculate confidence for a SELL signal."""
        confidence = 0.5  # Base confidence
        
        # ADX strength contribution
        if adx_strength == TrendStrength.VERY_STRONG:
            confidence += 0.25
        elif adx_strength == TrendStrength.STRONG:
            confidence += 0.2
        elif adx_strength == TrendStrength.MODERATE:
            confidence += 0.1
        
        # Crossover distance
        crossover_pct = (crossover_value / current_price) * 100
        crossover_factor = min(crossover_pct / 1.0, 1.0)
        confidence += crossover_factor * 0.15
        
        # Price below EMA confirmation
        if current_price < ema_fast:
            confidence += 0.1
        
        return min(confidence, 0.95)
    
    def _check_close_conditions(
        self,
        current_price: float,
        trend: str,
        adx: float,
        adx_strength: TrendStrength,
    ) -> Optional[SignalType]:
        """
        Check if position should be closed.
        
        Args:
            current_price: Current market price
            trend: Current trend direction
            adx: Current ADX value
            adx_strength: Current ADX strength
            
        Returns:
            Close signal type or None
        """
        if not self._position_open:
            return None
        
        # Check stop loss / take profit
        if self._position_side == "long":
            # Stop loss check
            stop_loss = self._entry_price * (1 - self.config.stop_loss_pct / 100)
            if current_price <= stop_loss:
                logger.info(f"Long stop loss triggered: {current_price:.4f} <= {stop_loss:.4f}")
                return SignalType.CLOSE_LONG
            
            # Take profit check
            take_profit = self._entry_price * (1 + self.config.take_profit_pct / 100)
            if current_price >= take_profit:
                logger.info(f"Long take profit triggered: {current_price:.4f} >= {take_profit:.4f}")
                return SignalType.CLOSE_LONG
            
            # Trend reversal check
            if trend == "bearish":
                logger.info("Trend reversed to bearish, closing long")
                return SignalType.CLOSE_LONG
        
        elif self._position_side == "short":
            # Stop loss check
            stop_loss = self._entry_price * (1 + self.config.stop_loss_pct / 100)
            if current_price >= stop_loss:
                logger.info(f"Short stop loss triggered: {current_price:.4f} >= {stop_loss:.4f}")
                return SignalType.CLOSE_SHORT
            
            # Take profit check
            take_profit = self._entry_price * (1 - self.config.take_profit_pct / 100)
            if current_price <= take_profit:
                logger.info(f"Short take profit triggered: {current_price:.4f} <= {take_profit:.4f}")
                return SignalType.CLOSE_SHORT
            
            # Trend reversal check
            if trend == "bullish":
                logger.info("Trend reversed to bullish, closing short")
                return SignalType.CLOSE_SHORT
        
        # ADX weakening (trend losing strength)
        if adx_strength == TrendStrength.WEAK and adx < self.config.adx_threshold * 0.5:
            logger.info(f"ADX dropped significantly, closing position")
            if self._position_side == "long":
                return SignalType.CLOSE_LONG
            else:
                return SignalType.CLOSE_SHORT
        
        return None
    
    def update_position_state(self, signal: StrategySignal, entry_price: float):
        """
        Update internal position state.
        
        Args:
            signal: Signal that opened/modified position
            entry_price: Entry price
        """
        if signal.signal_type == SignalType.BUY:
            self._position_open = True
            self._position_side = "long"
            self._entry_price = entry_price
        elif signal.signal_type == SignalType.SELL:
            self._position_open = True
            self._position_side = "short"
            self._entry_price = entry_price
        elif signal.signal_type in [SignalType.CLOSE_LONG, SignalType.CLOSE_SHORT]:
            self._position_open = False
            self._position_side = None
            self._entry_price = 0.0
    
    def calculate_position_size(
        self,
        capital_usd: float,
        entry_price: float,
        stop_loss_price: float,
    ) -> float:
        """
        Calculate position size using 2% risk rule.
        
        Args:
            capital_usd: Total trading capital in USD
            entry_price: Planned entry price
            stop_loss_price: Stop loss price
            
        Returns:
            Position size in base currency
        """
        # Calculate risk amount (2% of capital)
        risk_amount = capital_usd * (self.config.risk_per_trade_pct / 100)
        
        # Calculate stop loss distance
        stop_distance_pct = abs((entry_price - stop_loss_price) / entry_price) * 100
        
        if stop_distance_pct == 0:
            logger.warning("Stop loss distance is 0, using minimum position")
            return capital_usd * 0.01 / entry_price
        
        # Position size = risk / stop distance
        position_value = risk_amount / (stop_distance_pct / 100)
        
        # Apply maximum position limit
        max_position_value = capital_usd * (self.config.max_position_pct / 100)
        position_value = min(position_value, max_position_value)
        
        # Convert to base currency
        position_size = position_value / entry_price
        
        logger.info(
            f"Position size: {position_size:.4f} (value=${position_value:.2f}, "
            f"risk=${risk_amount:.2f}, stop_dist={stop_distance_pct:.2f}%)"
        )
        
        return position_size
    
    def calculate_stop_loss(
        self,
        entry_price: float,
        signal_type: SignalType,
    ) -> float:
        """
        Calculate stop loss price.
        
        Args:
            entry_price: Entry price
            signal_type: BUY or SELL
            
        Returns:
            Stop loss price
        """
        if signal_type == SignalType.BUY:
            return entry_price * (1 - self.config.stop_loss_pct / 100)
        else:
            return entry_price * (1 + self.config.stop_loss_pct / 100)
    
    def calculate_take_profit(
        self,
        entry_price: float,
        signal_type: SignalType,
    ) -> float:
        """
        Calculate take profit price.
        
        Args:
            entry_price: Entry price
            signal_type: BUY or SELL
            
        Returns:
            Take profit price
        """
        if signal_type == SignalType.BUY:
            return entry_price * (1 + self.config.take_profit_pct / 100)
        else:
            return entry_price * (1 - self.config.take_profit_pct / 100)
